### ISSUE TITLE
Putty generated Key unknown

### ISSUE THREAD

**Issue by riwich** [LukeGus/Termix#47]
If I try to add a connection and upload a Putty generated key in the Form "Authentication Tab / Method SSH Key", the result ist: 2Change UNKNOWN Key File".

![Image](https://github.com/user-attachments/assets/72347ebd-7966-4cdc-9888-f4e9737c21e9)

And, of course the connection is not working. Error is: 
```
*** Socket connection error: websocket error ***

```
All my servers have a Putty-generated Key...  So, I'm pretty lost with Termix now..
Currently I'm working with Putty, where this setup is working, of course... And with  "MobaXterm" it's worling too. Ideas?

Thanks
Thomas

**Comment by cradermacher** [comment]
Same to me. I use a .ppk File as Key. With putty this works, but Termix strucks.

Regards
Christian

**Comment by LukeGus** [comment]
Interesting, I've never come across this issue. You may have seen that I'm working on completely rebuilding Termix in TypeScript. Hopefully, this issue will be resolved once the new version is released, hopefully by the end of the month. I have yet to encounter this issue in the new version of Termix. Please let me know if you learn more, and I'll see what I can do in the meantime.

**Comment by LukeGus** [comment]
This issue has been fixed in Termix version 1.0 which includes a complete rewrite of the entire project.

**Comment by Lokowitz** [comment]
I tryied with version 1.1.1 but app is crashing. Does some one else got it working?

```
termix  | /app/node_modules/ssh2/lib/client.js:261
termix  |         throw new Error(`Cannot parse privateKey: ${privateKey.message}`);
termix  |         ^
termix  | 
termix  | Error: Cannot parse privateKey: Unsupported key format
termix  |     at Client.connect (/app/node_modules/ssh2/lib/client.js:261:15)
termix  |     at handleConnectToHost (file:///app/dist/backend/ssh/ssh.js:278:17)
termix  |     at WebSocket.<anonymous> (file:///app/dist/backend/ssh/ssh.js:51:17)
termix  |     at WebSocket.emit (node:events:517:28)
termix  |     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1220:20)
termix  |     at Receiver.emit (node:events:517:28)
termix  |     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:596:14)
termix  |     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:496:10)
termix  |     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:167:16)
termix  |     at Receiver._write (/app/node_modules/ws/lib/receiver.js:94:10)
termix  | 
termix  | Node.js v18.20.8
termix exited with code 0
```

**Comment by LukeGus** [comment]
> Edit: [@LukeGus](https://github.com/LukeGus) not sure if you got informed because it’s already closed.
> 
> I tryied with version 1.1.1 but app is crashing. Does some one else got it working?
> 
> ```
> termix  | /app/node_modules/ssh2/lib/client.js:261
> termix  |         throw new Error(`Cannot parse privateKey: ${privateKey.message}`);
> termix  |         ^
> termix  | 
> termix  | Error: Cannot parse privateKey: Unsupported key format
> termix  |     at Client.connect (/app/node_modules/ssh2/lib/client.js:261:15)
> termix  |     at handleConnectToHost (file:///app/dist/backend/ssh/ssh.js:278:17)
> termix  |     at WebSocket.<anonymous> (file:///app/dist/backend/ssh/ssh.js:51:17)
> termix  |     at WebSocket.emit (node:events:517:28)
> termix  |     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1220:20)
> termix  |     at Receiver.emit (node:events:517:28)
> termix  |     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:596:14)
> termix  |     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:496:10)
> termix  |     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:167:16)
> termix  |     at Receiver._write (/app/node_modules/ws/lib/receiver.js:94:10)
> termix  | 
> termix  | Node.js v18.20.8
> termix exited with code 0
> ```

Interesting, as the error shows that whatever key you're using is unsupported. Would you mind sharing the type of the key and its file extension? Don't send me the actual key, I'm just interested in its format. Also, does it have a password?

**Comment by Lokowitz** [comment]
@LukeGus
It is a .ppk file, generated from putty. 
It is necessary for logging in into a strato vps. Only the user name and this file is needed, no password.

<img width="455" height="447" alt="Image" src="https://github.com/user-attachments/assets/2b140eb9-fd5e-4554-8a6a-53a9fe3dfb7c" />

<img width="648" height="457" alt="Image" src="https://github.com/user-attachments/assets/5803b819-1788-4d71-8226-6dea70b2e0b5" />

**Comment by Lokowitz** [comment]
@LukeGus 

With Version 1.5.0 still an issue
`[ERROR] [🖥️] SSH key format error: Invalid private key format`
